const express=require('express');
const cors=require('cors');
const multer=require('multer');
const fs=require('fs');
const path=require('path');
const crypto=require('crypto');
const app=express();
const PORT=process.env.PORT||8080;
const PAYMENT_NUMBER=process.env.PAYMENT_NUMBER||'01118980717';
const DATA=path.join(__dirname,'data.json');
const UP=path.join(__dirname,'uploads');
if(!fs.existsSync(UP))fs.mkdirSync(UP,{recursive:true});
if(!fs.existsSync(DATA))fs.writeFileSync(DATA,JSON.stringify({users:{},payments:{}},null,2));
const read=()=>JSON.parse(fs.readFileSync(DATA,'utf8'));
const write=x=>fs.writeFileSync(DATA,JSON.stringify(x,null,2));
app.use(cors());app.use(express.json());app.use('/uploads',express.static(UP));
const upload=multer({dest:UP});
app.get('/api/config',(req,res)=>res.json({paymentNumber:PAYMENT_NUMBER,methods:['محفظة إلكترونية','InstaPay'],trialDays:7}));
app.post('/api/register',(req,res)=>{const {email,name}=req.body||{};if(!email)return res.status(400).json({error:'email مطلوب'});const d=read();if(!d.users[email])d.users[email]={id:crypto.randomUUID(),name:name||'',email,createdAt:new Date().toISOString(),trialUntil:new Date(Date.now()+7*86400000).toISOString(),activeUntil:null};write(d);res.json(d.users[email]);});
app.get('/api/status/:email',(req,res)=>{const d=read(),u=d.users[req.params.email];if(!u)return res.status(404).json({error:'المستخدم غير موجود'});const now=Date.now();res.json({...u,trialActive:new Date(u.trialUntil).getTime()>now,subscriptionActive:!!u.activeUntil&&new Date(u.activeUntil).getTime()>now});});
app.post('/api/payment',upload.single('receipt'),(req,res)=>{const {email,method,reference}=req.body||{};if(!email||!method)return res.status(400).json({error:'بيانات الدفع ناقصة'});const d=read();if(!d.users[email])return res.status(404).json({error:'المستخدم غير موجود'});const id=crypto.randomUUID();d.payments[id]={id,email,method,reference:reference||'',receipt:req.file?'/uploads/'+path.basename(req.file.path):null,status:'pending',createdAt:new Date().toISOString()};write(d);res.json({ok:true,id,status:'pending'});});
app.get('/api/admin/payments',(req,res)=>{const d=read();res.json(Object.values(d.payments).sort((a,b)=>b.createdAt.localeCompare(a.createdAt)));});
app.post('/api/admin/payments/:id/approve',(req,res)=>{const d=read(),p=d.payments[req.params.id];if(!p)return res.status(404).json({error:'الطلب غير موجود'});p.status='approved';const days=Number(req.body?.days||30);d.users[p.email].activeUntil=new Date(Date.now()+days*86400000).toISOString();write(d);res.json({ok:true,user:d.users[p.email]});});
app.post('/api/admin/payments/:id/reject',(req,res)=>{const d=read(),p=d.payments[req.params.id];if(!p)return res.status(404).json({error:'الطلب غير موجود'});p.status='rejected';write(d);res.json({ok:true});});
app.listen(PORT,()=>console.log(`SurveyQuant backend on :${PORT}`));
